### ISSUE TITLE
GridPACK won't build with PETSc 3.18.x

### ISSUE THREAD

**Issue by wperkins** [GridOPTICS/GridPACK#116]
The ExaLearn project has discovered that GridPACK won't build with PETSc 3.18.x.  Here is the error message:
```
/qfs/projects/ecp_exalearn/hsharma/PACKAGE/GridPACK/src/math/petsc/ga_matrix.cpp: In function ‘PetscErrorCode MatSetOperations_DenseGA(Mat)’:
/qfs/projects/ecp_exalearn/hsharma/PACKAGE/GridPACK/src/math/petsc/ga_matrix.cpp:895:34: error: ‘MATOP_MAT_MULT’ was not declared in this scope; did you mean ‘MATOP_MAT_SOLVE’?
  895 |   ierr = MatShellSetOperation(A, MATOP_MAT_MULT, (void(*)(void))MatMatMult_DenseGA); CHKERRQ(ierr);
      |                                  ^~~~~~~~~~~~~~
      |                                  MATOP_MAT_SOLVE
make[2]: *** [math/CMakeFiles/gridpack_math.dir/petsc/ga_matrix.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
This is in the GA-based dense matrix code that was added when PETSc did not have support for dense matrices in parallel.  It could probably just be changed to `MATOP_MAT_MULT_NUMERIC`, but I'm not sure of the difference.

**Comment by abhyshr** [comment]
> 

From the function pointer name `MatMatMult_DenseGA`, it seems like the operation you want to set is matrix-matrix multiply. [include/petscmat.h](https://petsc.org/main/include/petscmat.h.html) shows there is no `MATOP_MAT_MULT` in PETSc 3.18. There is a symbolic `MATOP_MATMAT_MULT_SYMBOLIC` and numeric `MATOP_MATMAT_MULT_NUMERIC`. synbolic computes the storage required for the new matrix and numeric does the matrix-matrix multiplication. You'll need to implement both these operations for your shell matrix now with PETSc 3.18. 

Having said that, if `MatDense_GA` is not used for any application in GridPACK then I think it would be better to remove it.

**Comment by wperkins** [comment]
> Having said that, if `MatDense_GA` is not used for any application in GridPACK then I think it would be better to remove it.

Agreed.

**Comment by wperkins** [comment]
Closing this. With the merge of #164, GridPACK can use PETSc >= 3.14.x.
